### ISSUE TITLE
fails to run after clean install in various containers

### ISSUE THREAD

**Issue by Stefan-J-Hanke** [sw360/capycli#16]
Hi,

I tried to run the `capycli` command in fresh container images

- apt update
- apt install -y pip
- pip install capycli

results are the same in both **debian:stable** and **buildpack-deps:stable**

![image](https://github.com/sw360/capycli/assets/54064208/e13a31e8-b03b-47d1-b722-92d1694d0d6b)

I can't even run with **--help** - same error. Am I doind something wrong?

**Comment by tngraf** [comment]
Probably you are using an older Python version. CaPyCLI 2.0.0.dev8 works properly with Python 3.10 and Python 3.11.  
The issues with Python 3.8 and 3.9 have already been fixed, but we have not released a new version yet.

**Comment by tngraf** [comment]
CaPyCLI, 2.0.0 has been released. This includes support for Python 3.8 - 3.11.
Please use Debian images that support one of these Python versions.
