### ISSUE TITLE
create project fails if empty

### ISSUE THREAD

**Issue by ericbl** [sw360/capycli#17]
running the capycli on a new and empty project resulted in this exception:
```
../capycli/project/create_project.py", line 97, in update_project
    print("  " + str(len(project["_embedded"]["sw360:releases"])) + " releases in project after update")
```
was on capycli 1.91

but the code in 2.0 will suffer with the same issue here:
https://github.com/sw360/capycli/blob/main/capycli/project/create_project.py#L77

if no release yet is attached to a project, it will also fails.
-> add a check if "sw360:releases" in project["_embedded"]  as in l.65

**Comment by tngraf** [comment]
Works for me with an empty project using ```project create``` or ```project update```.  
SW360 version 17.0.0-SNAPSHOT | Branch: masterct (0fc88d5) | Build time: 2023-06-03T16:33:57Z
