### ISSUE TITLE
refactor testcases to directly use pytest

### ISSUE THREAD

**Issue by gernot-h** [sw360/capycli#39]
We already [use pytest](https://github.com/sw360/capycli/blob/d9b4a84c7e3861cfb289c3e03c9654a19723dd19/.github/workflows/unit-tests.yml#L41), but still [derive our test classes from traditional unittest](https://github.com/sw360/capycli/blob/d9b4a84c7e3861cfb289c3e03c9654a19723dd19/tests/test_base.py#L66).

This is [perfectly valid](https://docs.pytest.org/en/7.1.x/how-to/unittest.html), but we cannot use some nice pytest features that way. As an example, pytest has [built-in support for capturing stdout/stderr](https://docs.pytest.org/en/7.1.x/how-to/capture-stdout-stderr.html), so we could drop [our own implementation](https://github.com/sw360/capycli/blob/d9b4a84c7e3861cfb289c3e03c9654a19723dd19/tests/test_base.py#L87). I also like [pytest's more intuitive assert syntax](https://docs.pytest.org/en/7.1.x/how-to/assert.html#assert).

Concrete reason why I ask is that I recently extended our own capture_stdout implementation [to support an arbitrary number of arguments](https://github.com/sw360/capycli/commit/c3171b50f4cc6c43d1caf9a82c7e0faaef86206d) and now I noticed that with our own implemenation, I can't capture stdout and check the return value at the same time. All of that would already be available from pytest.

It would however mean a larger rework, but I think it would be possible to migrate file by file where needed.

If you're interested, @tngraf, I could try adding my new tests for #33 in pytest-style or also rewrite the "project createbom" tests in #37 to pytest style.

**Comment by gernot-h** [comment]
We now have a first pytest-based class in https://github.com/sw360/capycli/blob/main/tests/test_create_bom.py.

I would however suggest to keep this issue open for a while until at least some more files have been migrated to pytest and/or we added some sentences to https://github.com/sw360/capycli/blob/main/Contributing.md#testing about the future direction.

**Comment by gernot-h** [comment]
@tngraf, what do you think, do you want to keep both variants (unittest and pytest-based classes) in the long run, so we can choose case by case or should we strive to migrate all tests to pytest over time?

**Comment by tngraf** [comment]
I did some tests with pytests assert and console output capturing. I agree that these are nice features, but 
* we have many unit tests for capycli that work very well and do not need this functionality
* you cannot debug unit tests that use pytest's console output capturing ... at least not ina an easy way

I will not block someone from using ```assert``` and pytest features, but at the moment I see no reason to rewirte all unit tests.

**Comment by gernot-h** [comment]
Ok, then let's document it like that.
