### ISSUE TITLE
BOM conversion from legacy to capycli not correct

### ISSUE THREAD

**Issue by sachinshaji** [sw360/capycli#64]
When we convert BOM from legacy to capycli [ capycli bom convert  -i <input.json> -if legacy -o <output.json> -of capycli ] "SourceUrl" from legacy BOM is getting converted to "source archive (local copy)" in capycli BOM.

What should be the actual conversion?
It should be converted to "source archive (download location)"

How to replicate the issue?
Take a simple capycli BOM and convert to legacy BOM and then again convert to capycli BOM. The 2 capycli BOM output will be different in this case. Attaching a simple capycli BOM to try.

Resolution of the issue?
PR: https://github.com/sw360/capycli/pull/63

{
    "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json",
    "bomFormat": "CycloneDX",
    "specVersion": "1.4",
    "serialNumber": "urn:uuid:12432b27-1088-4a8d-a85c-948c1e1812bc",
    "version": 1,
    "metadata": {
      "timestamp": "2024-04-13T06:17:33.177283+00:00",
      "tools": [
        {
          "vendor": "Siemens AG",
          "name": "CaPyCLI",
          "version": "2.3.0",
          "externalReferences": [
            {
              "url": "https://github.com/sw360/capycli",
              "type": "website"
            }
          ]
        },
        {
          "vendor": "Siemens AG",
          "name": "standard-bom",
          "version": "2.0.0",
          "externalReferences": [
            {
              "url": "https://code.siemens.com/sbom/standard-bom",
              "type": "website"
            }
          ]
        }
      ],
      "licenses": [
        {
          "license": {
            "id": "CC0-1.0"
          }
        }
      ],
      "properties": [
        {
          "name": "siemens:profile",
          "value": "capycli"
        }
      ]
    },
    "components": [
      {
        "type": "library",
        "bom-ref": "pkg:pypi/click@8.1.7",
        "name": "click",
        "version": "8.1.7",
        "description": "Composable command line interface toolkit",
        "licenses": [
          {
            "license": {
              "name": "BSD-3-Clause"
            }
          }
        ],
        "purl": "pkg:pypi/click@8.1.7",
        "externalReferences": [
          {
            "url": "click-8.1.7-py3-none-any.whl",
            "comment": "relativePath",
            "type": "distribution"
          },
          {
            "url": "click-8.1.7.tar.gz",
            "comment": "source archive (local copy)",
            "type": "distribution"
          },
          {
            "url": "https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl",
            "comment": "binary (download location)",
            "type": "distribution"
          },
          {
            "url": "https://files.pythonhosted.org/packages/96/d3/f04c7bfcf5c1862a2a5b845c6b2b360488cf47af55dfa79c98f6a6bf98b5/click-8.1.7.tar.gz",
            "comment": "source archive (download location)",
            "type": "distribution"
          },
          {
            "url": "https://pypi.org/project/click/",
            "comment": "PyPi URL",
            "type": "distribution"
          },
          {
            "url": "https://palletsprojects.com/p/click/",
            "type": "website"
          }
        ],
        "properties": [
          {
            "name": "siemens:primaryLanguage",
            "value": "Python"
          }
        ]
      }
    ],
    "dependencies": [
        {
            "ref": "pkg:pypi/click@8.1.7",
            "dependsOn": []
          }
    ]
}

**Comment by tngraf** [comment]
PR has been merged.
