### ISSUE TITLE
CaPyCLI reports an error when creating an SBOM from SW360

### ISSUE THREAD

**Issue by tngraf** [sw360/capycli#66]
CaPyCLI reports an error when generating an SBOM from a project on SW360 when this project contains a component with more than on package-url. Actually it is the `packageurl` component which reports the error.

**Comment by gernot-h** [comment]
Hmm, I'm quite sure this has worked in the past. Perhaps the API behaviour has changed?

**Comment by tngraf** [comment]
> Hmm, I'm quite sure this has worked in the past. Perhaps the API behaviour has changed?

Actually I did not check all details. In the case that was reported there was somehow a blank the first character in the purl string ... and this will not get accepted by the packageurl library.
