### ISSUE TITLE
Check compatibility with Python 3.8 and 3.9

### ISSUE THREAD

**Issue by tngraf** [sw360/capycli#7]
We we run the unit test on Python 3.8 and 3.9 there are error messages...

**Comment by gernot-h** [comment]
Can you add a pointer to the corresponding Github Aciton here? I'm not really fluent with those yet. :)

**Comment by tngraf** [comment]
> Can you add a pointer to the corresponding Github Aciton here? I'm not really fluent with those yet. :)

The magic is in line 22 of `unit-test.yml`:

```code
python-version: ["3.8", "3.9", "3.10", "3.11"]
```

It says that the steps shall be run for each of the specified Python versions.

Anyway, after spending hours to add type information to `sw360python`, I also updated `capycli`.
The trick is to use `List`, `Tuple` and `Dict` from `typing` and **not** to use the built in types `list`, `tuple` and `dict`.
