### ISSUE TITLE
Support CycloneDX 1.6 / Siemens Standard BOM 3

### ISSUE THREAD

**Issue by tngraf** [sw360/capycli#84]

**Comment by gernot-h** [comment]
I guess this would be a good opportunity to also update cyclonedx-python-lib. ;-)

**Comment by tngraf** [comment]
@gernot-h done 😄 It has been updated to the latest version 8.0.0. But even this version does not yet support `definition/standard` so that we still cannot create fully valid Siemens Standard BOM 3 SBOMs.  
Many things have chnaged in the library so it will still take some time until we have a first running version.

**Comment by gernot-h** [comment]
> @gernot-h done 😄 It has been updated to the latest version 8.0.0. But even this version does not yet support `definition/standard` so that we still cannot create fully valid Siemens Standard BOM 3 SBOMs. Many things have chnaged in the library so it will still take some time until we have a first running version.

Cool, let me know if I can help!
