### ISSUE TITLE
Clarification of FORCE_EXIT option

### ISSUE THREAD

**Issue by bjoernbusch** [sw360/capycli#85]
In the documentation of the CLI, it looks like there is a generic FORCE_EXIT option, but when I use this in combination with `bom map ... --forceexit 0` the call exits with `80` anyway. When looking at the code, it looks like this option is only considered in the context of a security vulnerability report.

Could this be planned as an enhancement to consider the FORCE_EXIT option for all calls? If not, could the documentation be updated? Or maybe I just don't understand the code :)

Thanks!

**Comment by gernot-h** [comment]
@bjoernbusch, I think applying the option to more/all subcommands might be a good idea. We're always open for PRs, perhaps start small with your actual use case, then we can think about extending it to more commands over time. :-)

@tngraf already started documenting the current restrictions which confirms your assumption, see #91.

**Comment by bjoernbusch** [comment]
thanks for the clarification, I will try to dive into python and conjure up a PR :)

**Comment by gernot-h** [comment]
> thanks for the clarification, I will try to dive into python and conjure up a PR :)

Great, thanks, @bjoernbusch! Please don't wait until you have a final implementation, but let us know as soon as you have an idea how to implement it, either by describing your idea here or by providing an early draft PR! And don't hesitate to ask here or contact me directly if you have questions. ;)

This is just to avoid you put too much effort into an approach we probably need to adapt later, e.g. after clarifying the open points I mentioned in #91. As Thomas is probably not available for clarifications in the next days, it might take some time until we have full clarity here.
